# frozen_string_literal: true

# T-36 — a deterministic, engine-neutral snapshot of the database schema.
#
# Run inside a Redmine checkout: `bundle exec rails runner <this file> [out_path]`
# (`script/migrate_updown.sh` is the only caller that matters).
#
# --- WHY NOT `rake db:schema:dump` ---
#
# `db/schema.rb` is Rails-version-dependent in ways that have nothing to do with this
# plugin: `t.datetime` gained a default precision in Rails 7, `create_table` gained and
# lost options across 6.1 → 8.1, and the file is regenerated by Redmine's own
# `redmine:plugins:migrate` task (`lib/tasks/redmine.rake:155`) — so it is both noisy and
# already written by the thing under test. It is also PostgreSQL/MySQL-divergent for
# column defaults.
#
# This emits sorted lines instead. Diffing two of them says WHICH object appeared or
# disappeared, in one line, on any of the three engines this plugin runs on.
#
# --- WHAT IS AND IS NOT NORMALISED ---
#
# `sql_type` is kept verbatim, because the whole point of a down-migration test is to
# notice a column that came back as a different type. Column DEFAULTS are kept too. What is
# normalised is only ORDER: tables, columns within a table, and indexes are each sorted, so
# a snapshot does not depend on the order the database happens to list things in — which is
# not stable on any of the three engines (CLAUDE.md §6).
#
# `schema_migrations` rows for THIS PLUGIN are emitted as `PLUGINMIGRATION` lines. FR-69
# asks for "no plugin row in `plugin_schema_info`"; that table does not exist on any
# supported Redmine (measured — see `script/migrate_updown.sh`), and the real bookkeeping is
# a `schema_migrations` row of the form `<version>-<plugin_id>`
# (`redmine/lib/redmine/plugin.rb:553-555`). Emitting them here is what lets the caller
# assert the requirement's INTENT against the mechanism that actually exists.

PLUGIN_ID = 'redmine_reporter_dashboards'

connection = ActiveRecord::Base.connection
lines = []

connection.tables.sort.each do |table|
  lines << "TABLE #{table}"

  connection.columns(table).sort_by(&:name).each do |column|
    lines << format(
      'COLUMN %<table>s.%<name>s type=%<sql_type>s null=%<null>s default=%<default>s',
      table: table, name: column.name, sql_type: column.sql_type,
      null: column.null, default: column.default.inspect
    )
  end

  connection.indexes(table).sort_by(&:name).each do |index|
    lines << format(
      'INDEX %<table>s.%<name>s unique=%<unique>s columns=%<columns>s',
      table: table, name: index.name, unique: index.unique,
      columns: Array(index.columns).join(',')
    )
  end
end

# Deliberately only this plugin's rows: another plugin's migrations are not this job's
# business, and including them would make the comparison fail for somebody else's reason.
sm_table = connection.quote_table_name(
  ActiveRecord::Base.connection.pool.schema_migration.table_name
)
connection.select_values("SELECT version FROM #{sm_table}")
          .select { |v| v.to_s.end_with?("-#{PLUGIN_ID}") }
          .sort
          .each { |v| lines << "PLUGINMIGRATION #{v}" }

output = "#{lines.join("\n")}\n"

path = ARGV[0]
if path && !path.empty?
  File.binwrite(path, output)
else
  $stdout.write(output)
end
